apiVersion: v1
kind: Service
metadata:
  name: hellorocketchat-app
spec:
  selector:
    app: hellorocketchat-app
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellorocketchat-app
spec:
  selector:
    matchLabels:
      app: hellorocketchat-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hellorocketchat-app
    spec:
      containers:
      - name: hellorocketchat-app
        image: mahdiraghib/hellorocketchat:1.0
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 5001